baseURL = 'https://neromaglio.github.io'
locale = 'en-us'
title = 'Davide Gadioli, PhD'
theme = 'hugo-profile'

# Multilingual configuration
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[params]
  description = 'About me'
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"
  useBootstrapCDN = false
  mathjax = true
  animate = true

[params.navbar]
  brandName = "Davide Gadioli, PhD"
  disableSearch = true

