baseURL = 'https://neromaglio.github.io'
locale = 'en-us'
title = 'Davide Gadioli, PhD'
theme = 'hugo-profile'

# Multilingual configuration
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[params]
  description = 'About me'
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"
  useBootstrapCDN = false
  mathjax = true
  animate = true

[params.navbar]
  disableSearch = true

[params.navbar.stickyNavBar]
  enable = true
  showOnScrollUp = true

[params.theme]
  disableThemeToggle = true

[[menu.main]]
  identifier = "about"
  name = "Bio"
  url = "/#about"
  weight = 10

[[menu.main]]
  identifier = "main-research"
  name = "Research"
  url = "/#main-research"
  weight = 25

[[menu.main]]
  identifier = "awards"
  name = "Awards"
  url = "/#awards"
  weight = 30

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/#projects"
  weight = 40