baseURL = 'https://neromaglio.github.io'
locale = 'en-us'
title = 'Personal website'
theme = 'hugo-profile'

# Multilingual configuration
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[params]
  description = 'About me'
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"
  useBootstrapCDN = false
  mathjax = true
  animate = true

[params.navbar]
  brandName = "D. Gadioli, PhD"
  disableSearch = true

[params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Davide."
  subtitle = "I optimize scientific applications for HPC."
  content = "A Junior Assistant Professor in Politecnico"
